/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package challenge.morsecode;

import java.awt.*;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_SPACE;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author MLachaw
 */
public class Ramka extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Ramka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  private static String smorse(String plaintext)
    {
        String out = "";

        Map<Character, String> morseCodeBook = new HashMap<>();
        morseCodeBook.put('a', ".- ");
        morseCodeBook.put('b', "-.. ");
        morseCodeBook.put('c', "-.-. ");
        morseCodeBook.put('d', "-.. ");
        morseCodeBook.put('e', ". ");
        morseCodeBook.put('f', "..-. ");
        morseCodeBook.put('g', "--. ");
        morseCodeBook.put('h', ".... ");
        morseCodeBook.put('i', ".. ");
        morseCodeBook.put('j', ".--- ");
        morseCodeBook.put('k', "-.- ");
        morseCodeBook.put('l', ".-.. ");
        morseCodeBook.put('m', "-- ");
        morseCodeBook.put('n', "-. ");
        morseCodeBook.put('o', "--- ");
        morseCodeBook.put('p', ".--. ");
        morseCodeBook.put('q', "--.- ");
        morseCodeBook.put('r', ".-. ");
        morseCodeBook.put('s', "... ");
        morseCodeBook.put('t', "- " );
        morseCodeBook.put('u', "..- ");
        morseCodeBook.put('v', "...- ");
        morseCodeBook.put('w', ".-- ");
        morseCodeBook.put('x', "-..- ");
        morseCodeBook.put('y', "-.-- ");
        morseCodeBook.put('z', "--.. ");
        morseCodeBook.put('ą', ".- ");
        morseCodeBook.put('ć', "-.-. ");
        morseCodeBook.put('ę', ". ");
        morseCodeBook.put('ł', ".-.. ");
        morseCodeBook.put('ń', "-. ");
        morseCodeBook.put('ó', "---");
        morseCodeBook.put('ś', "... ");
        morseCodeBook.put('ż', "--..-. ");
        morseCodeBook.put('ż', "--.. ");
        morseCodeBook.put('ź', "--.. ");
        morseCodeBook.put(' ', "• — • • —");
        

        for (int i = 0; i < plaintext.length(); i++)
        {
            if (Character.isLetter(plaintext.charAt(i)))
            {
                out = out.concat(morseCodeBook.get(Character.toLowerCase(plaintext.charAt(i))));
            }
        }

        return out;
    }

    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Tłumacz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Wyczyść");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String text = jTextArea1.getText().toUpperCase();
        String x = smorse(text);
        jTextArea2.setText(x);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea1.setText("");
        jTextArea2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
